<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Flight extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'flight_number',
        'airline_id',
        'plane_id',
        'origin_id',
        'destination_id',
        'departure_time',
        'arrival_time',
        'available_seats',
        'total_seats',
        'price',
        'status',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($flight) {
            $flight->available_seats = $flight->total_seats;
            $flight->status = config('status.flight.scheduled');
        });

    }


    public function airline(): BelongsTo
    {
        return $this->belongsTo(Airline::class);
    }

    public function plane(): BelongsTo
    {
        return $this->belongsTo(Plane::class);
    }

    public function origin(): BelongsTo
    {
        return $this->belongsTo(Airport::class, 'origin_id', 'id');
    }

    public function destination(): BelongsTo
    {
        return $this->belongsTo(Airport::class, 'destination_id', 'id');
    }

}
